name: RetroConomy
version: 1.0.0
main: com.github.sanctum.retro.RetroConomy
api-version: 1.13
depend: [ Labyrinth ]
softdepend: [ Vault, Enterprise ]
authors: [ Hempfest, ms5984 ]
description: An advanced spigot vault & enterprise economy provider.
loadbefore:
  - EnchantGui
  - EnchantGUI