name: RetroConomy
version: ${project.version}
main: com.github.sanctum.retro.RetroConomy
api-version: 1.13
depend: [ Labyrinth ]
softdepend: [ Vault, Enterprise ]
authors: [ Hempfest, ms5984 ]
description: An advanced Enterprise and Vault economy provider for Bukkit.
loadbefore:
  - EnchantGui
  - EnchantGUI